package org.genshinimpact.webserver.enums;

// Imports
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.Getter;

@SuppressWarnings("unused")
public enum ReportErrorCode {
    NONE(0),

    // Dispatch
    NETWORK_DISCONNECT_GO_BACK_HOME(4001),
    NETWORK_RECONNECT_GATE_FAIL(4002),
    NETWORK_CONNECT_CLIENT_NOT_NULL(4003),
    NETWORK_CONNECT_CLIENT_INIT_FAIL(4004),
    NETWORK_LOGIN_EXCEPTION(4005),
    NETWORK_CONNECT_GATE_FAIL(4006),
    NETWORK_DISCONNECT_STATE(4007),
    NETWORK_SEND_PACKET_ERROR(4008),
    NETWORK_RECEIVE_PACKET_ERROR(4009),
    NETWORK_EXCEPTION(4010),
    NETWORK_ERROR(4011),
    DISPATCH_GLOBAL_GET_TIMEOUT(4201),
    DISPATCH_GLOBAL_GET_ERROR(4202),
    DISPATCH_GLOBAL_PARSE_EXCEPTION(4203),
    DISPATCH_GLOBAL_PARSE_INVALID(4204),
    DISPATCH_GLOBAL_CONFIG_PARSE_FAIL(4205),
    DISPATCH_REGION_GET_TIMEOUT(4206),
    DISPATCH_REGION_GET_ERROR(4207),
    DISPATCH_REGION_PARSE_EXCEPTION(4208),
    DISPATCH_REGION_PARSE_INVALID(4209),
    DISPATCH_CONFIG_PARSE_EXCEPTION(4210),
    DISPATCH_GLOBAL_CONFIG_PARSE_INVALID(4211),
    DISPATCH_REGION_RSP_INVALID(4212),
    DISPATCH_REGION_ERR_WITH_CODE(4213),
    LOGIN_TOKEN_GET_FAIL(4301),
    LOGIN_PLAYER_LOGIN__FAIL(4302),
    LOGIN_ENTER_SCENE_READY_FAIL(4303),
    LOGIN_INIT_FINISH_FAIL(4304),
    LOGIN_ENTER_SCENE_DONE_FAIL(4305),
    LOGIN_POST_ENTER_SCENE_FAIL(4306),
    LOGIN_ENTER_TOKEN_INVALID(4307),
    LOGIN_TASK_TIMEOUT(4308),
    SDK_INIT_FAIL(4401),
    SDK_LOGIN_FAIL(4402),
    SDK_LOGOUT_FAIL(4403),
    SDK_PAY_FAIL(4404),
    SDK_GET_TIER_FAIL(4405),
    SDK_GET_MALL_PRODUCT_FAIL(4406),
    SDK_GET_BP_PRODUCT_FAIL(4407),
    SDK_HAS_PRODUCT_FAIL(4408),

    // Downloading resources
    Unknown(-9000),
    TimeOut(-9002),
    VerifyMd5OrFileSizeFailed(-9004),
    DiskFull(-9005),
    IOFailed(-9006),
    InvalidSavePath(-9007),
    InvalidRequest(-9008),
    Cancelled(-9009),
    FetchFileLengthFailed(-9010),
    DownloadLengthNotEqualToExpected(-9011),
    WebException_Success(-9100),
    WebException_NameResolutionFailure(-9101),
    WebException_ConnectFailure(-9102),
    WebException_ReceiveFailure(-9103),
    WebException_SendFailure(-9104),
    WebException_PipelineFailure(-9105),
    WebException_RequestCanceled(-9106),
    WebException_ProtocolError(-9107),
    WebException_ConnectionClosed(-9108),
    WebException_TrustFailure(-9109),
    WebException_SecureChannelFailure(-9110),
    WebException_ServerProtocolViolation(-9111),
    WebException_KeepAliveFailure(-9112),
    WebException_Pending(-9113),
    WebException_Timeout(-9114),
    WebException_ProxyNameResolutionFailure(-9115),
    WebException_UnknownError(-9116),
    WebException_MessageLengthLimitExceeded(-9117),
    WebException_CacheEntryNotFound(-9118),
    WebException_RequestProhibitedByCachePolicy(-9119),
    WebException_RequestProhibitedByProxy(-9120),
    NotSupportedException(-9201),
    NotAValidMethodOrArgumentException(-9202),
    AuthenticationOrDecryptionFailed(-9203),
    SharingViolation(-9204),
    CouldNotFindFile(-9205),
    AliveKeeperNotWorking(-9301),
    NextResMergeError(-9321),
    ResetAudioLangFileError(-9331),
    ApplyAudioDiffError(-9341),
    SaveDownloadLogError(-9351),
    OtherErrorInFilesDownloadManager(-9359),
    NotAllFilesInResVersionExist(-9901),
    NotAllFilesInDataVersionExist(-9902),
    NotAllFilesInSilenceVersionExist(-9903),
    CancelledByUser(-9904),
    CannotReachNetwork(-9905),
    CheckWritableFailed(-9906),
    NotEnoughSpace(-9907),
    VerifyMd5Failed(-9908),
    CopyRemoteVersionFileFailed(-9909),
    WriteRevisionFileFailed(-9910),
    DownloadRemoteVersionFileFailed(-9911),
    OverwriteOldFileFailed(-9912),
    DownloadStuck(-9913),
    NotAllDownloadFilesExist(-9991),
    DownloaderStatusFailed(-9992),
    DownloadUnexpectedException(-9999);

    @JsonValue @Getter private final int value;
    ReportErrorCode(int value) {
        this.value = value;
    }
}