package org.genshinimpact.webserver.enums;

// Imports
import com.fasterxml.jackson.annotation.JsonValue;
import lombok.Getter;

public enum Retcode {
    RETCODE_RATE_LIMIT_EXCEEDED(-503),
    RETCODE_INVALID_ACCOUNT(-216),
    RETCODE_INVALID_ACCOUNT_LOGIN_STATUS(-210),
    RETCODE_NETWORK_AT_RISK(-115),
    RET_LOGIN_NEW_LOCATION_FOUND(-111),
    RETCODE_GUEST_LOGIN_ERROR(-110),
    RETCODE_ACCOUNT_ANTIADDICT_LOGIN(-108),
    RETCODE_ACCOUNT_INVALID_FORMAT(-107),
    RETCODE_REQUEST_FAILED(-106),
    RETCODE_ACCOUNT_ERROR(-105),
    RETCODE_CONFIGURATION_ERROR(-104),
    RETCODE_PARAMETER_ERROR2(-103),
    RETCODE_PARAMETER_ERROR(-102),
    RETCODE_SYSTEM_ERROR(-101),
    RETCODE_FAIL(-1),
    RETCODE_SUCC(0),
    RETCODE_COMBO_INVALID_MODULE(4),
    RETCODE_COMBO_INVALID_KEY(6),
    RETCODE_COMBO_NO_CONFIG(7),
    RETCODE_ABTEST_AUTHENTICATION_FAILED(1002);

    @JsonValue @Getter private final int value;
    Retcode(int value) {
        this.value = value;
    }
}