package org.genshinimpact.gameserver.enums;

public enum VisionType {
    VISION_NONE,
    VISION_MEET,
    VISION_REBORN,
    VISION_REPLACE,
    VISION_WAYPOINT_REBORN,
    VISION_MISS,
    VISION_DIE,
    VISION_GATHER_ESCAPE,
    VISION_REFRESH,
    VISION_TRANSPORT,
    VISION_REPLACE_DIE,
    VISION_REPLACE_NO_NOTIFY,
    VISION_BORN,
    VISION_PICKUP,
    VISION_REMOVE,
    VISION_CHANGE_COSTUME,
    VISION_FISH_REFRESH,
    VISION_FISH_BIG_SHOCK,
    VISION_FISH_QTE_SUCC,
    VISION_CAPTURE_DISAPPEAR;

    public int getValue() {
        return this.ordinal();
    }
}